#!/bin/sh

DIRECTORY_NAME=${PWD##*/}
read -p "🔎 Container name: ($DIRECTORY_NAME): " -r

CONTAINER_NAME=${REPLY:-$DIRECTORY_NAME}
SVN_REPO=$(svn info --show-item url)

if [ ! "$(docker ps -q -f name=$CONTAINER_NAME)" ]; then
	if [ "$(docker ps -aq -f status=exited -f name=$CONTAINER_NAME)" ]; then
		# cleanup
		docker rm $CONTAINER_NAME
	fi

	docker run -dit --name $CONTAINER_NAME deuxhuithuit/push
fi

docker exec -it $CONTAINER_NAME /bin/bash /checkout.sh $SVN_REPO
docker exec -it $CONTAINER_NAME /bin/bash /root/project/deploy
