field: 9ee0fccd-4076-47c7-9e3c-6681d566922f # Modules
fieldLayouts:
  71676022-697f-4f12-b0bb-092412b6c42b:
    tabs:
      -
        elements:
          -
            fieldUid: 961c9d0d-88f0-4c4d-8dde-f3b86d825bb3 # Display Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b8b1c7d6-1ed3-479e-99d1-7c343ff69b9a # Media
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f59fba00-85f1-4e9f-a378-842461735f7f # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  961c9d0d-88f0-4c4d-8dde-f3b86d825bb3: # Display Title
    contentColumnType: text
    fieldGroup: null
    handle: displaytitle
    instructions: ''
    name: 'Display Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b8b1c7d6-1ed3-479e-99d1-7c343ff69b9a: # Media
    contentColumnType: string
    fieldGroup: null
    handle: media
    instructions: ''
    name: Media
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
        - video
      defaultUploadLocationSource: 'volume:011c9553-4860-4959-9f41-125b28b70821' # Assets
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:011c9553-4860-4959-9f41-125b28b70821' # Assets
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  f59fba00-85f1-4e9f-a378-842461735f7f: # Caption
    contentColumnType: text
    fieldGroup: null
    handle: caption
    instructions: ''
    name: Caption
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: media
name: Media
sortOrder: 2
