baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Craft Template'
primary: true
siteGroup: daecc81d-5ba3-4f93-a679-1a95d13c6c13 # Craft Template
sortOrder: 1
