contentColumnType: string
fieldGroup: 3ae933e0-0271-44cd-9d9c-a84684ecbd2e # Common
handle: sameAs
instructions: ''
name: 'Same As'
searchable: false
settings:
  contentTable: '{{%matrixcontent_sameas}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
